// Loaded only by browser-fixture.cjs. Run runBrowserChecks() in Chrome DevTools.
window.runBrowserChecks = async function () {
  const app = window.__crTest;
  const $ = selector => document.querySelector(selector);
  const pause = () => new Promise(resolve => setTimeout(resolve, 35));
  const check = (ok, message) => { if (!ok) throw new Error(message); };
  document.querySelectorAll('dialog[open]').forEach(dialog => dialog.close());
  await app.selectThread('fixture'); await pause();
  const timeline = $('#timeline');
  const push = async () => { for (let i=0;i<6;i++) { app.handleNotification('item/agentMessage/delta', {threadId:'fixture',turnId:'turn',itemId:'message-54',delta:'\nBrowser regression '+i}); await pause(); } };
  timeline.scrollTop=timeline.scrollHeight; await push();
  check(timeline.scrollTop>0 && timeline.scrollHeight-timeline.clientHeight-timeline.scrollTop<2, 'Streaming stopped following the bottom');
  timeline.scrollTop=700; await push(); check(timeline.scrollTop===700,'Streaming lost the reading position');
  app.openProjectFiles(); await pause(); await pause();
  check($('[data-project-entry]').dataset.projectEntryType==='directory','Folder order');
  const boxes=document.querySelectorAll('[data-project-select]'); boxes[0].click();boxes[1].click();
  check(app.state.projectFileSelection.size===2,'Mixed file/folder selection');
  await app.openProjectFile('/fixture/project/long.txt');
  check($('#projectPreviewMode').value==='code','Default source mode');
  check($('#projectFileCode').parentElement.scrollWidth <= $('#projectFileCode').parentElement.clientWidth+1,'Code wrapping overflow');
  await app.openProjectFile('/fixture/project/readme.md');$('#projectPreviewMode').value='formatted';app.renderProjectPreview();
  check(!!$('#projectFileRendered h1'),'Markdown heading not rendered');
  await app.openProjectFile('/fixture/project/data.json');$('#projectPreviewMode').value='formatted';app.renderProjectPreview();
  check($('#projectFileRendered').textContent.includes('\n  "name"'),'JSON not formatted');
  $('#projectFilesDialog').close();app.openStatusDialog();$('#openCodexSettings').click();await pause();await pause();
  const input=$('#codexConfigSource'); const saved=input.value;
  input.value += '\n# browser editor check\n'; input.dispatchEvent(new Event('input'));
  check($('#codexConfigHighlight').textContent.includes('# browser editor check'),'Editor text not synchronized');
  check(!!$('#codexConfigHighlight .token-comment'),'TOML syntax highlighting');
  const styles=getComputedStyle(input), overlay=getComputedStyle($('#codexConfigHighlight'));
  check(styles.font===overlay.font&&styles.padding===overlay.padding,'Editor caret/highlight alignment');
  input.value=Array.from({length:80},(_,i)=>`key${i} = "value"`).join('\n');input.dispatchEvent(new Event('input'));
  input.scrollTop=300;input.dispatchEvent(new Event('scroll'));check($('#codexConfigHighlight').scrollTop===input.scrollTop,'Editor scroll not synchronized');
  input.value=saved;input.dispatchEvent(new Event('input'));
  $('#showCodexAuth').click();check(!$('#authEditorPanel').hidden&&$('#configEditorPanel').hidden,'Auth tab switch');
  check(!!$('#codexAuthHighlight .token-string'),'JSON highlighting');
  $('#configFileTab').click();
  const heights=[...document.querySelectorAll('#codexSettingsDialog button')].map(button=>button.getBoundingClientRect().height);
  check(heights.every(height=>Math.abs(height-40)<1),'Inconsistent settings button heights');
  check(document.documentElement.scrollWidth<=innerWidth,'Page horizontal overflow');
  $('#codexSettingsDialog').close();await pause();
  check(!input.value&&!$('#codexAuthSource').value,'Credentials retained after close');
  return {viewport:[innerWidth,innerHeight],streaming:'bottom and reading position preserved',files:'sorted, mixed selection, wrap, Markdown, JSON',editor:'TOML/JSON highlighting, tab, scroll, caret alignment, credential cleanup',buttons:'40px',overflow:0};
};
